branches:
  - "release-+([0-9])?(.{+([0-9]),x}).x"
  - "master"
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - ["@semantic-release/changelog", { changelogFile: "CHANGELOG.md", changelogTitle: "Changelog" }]
  - "@semantic-release/git"
  - "@semantic-release/github"
