name: Release

on:
  push:
    branches:
      - master
      - release-*

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      packages: none

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Perform semantic release
      # https://github.com/cycjimmy/semantic-release-action
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        with:
          semantic_version: 18
          extra_plugins: |
            @semantic-release/changelog@6.0.1
            @semantic-release/git@10.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
